- name: Install custom facts
  hosts: database
  become: yes
  tasks:

    - name: Create directory for ansible custom facts
      file:
        state: directory
        recurse: yes
        path: /etc/ansible/facts.d

    - name: Install custom fact
      copy:
        src: custom.fact
        dest: /etc/ansible/facts.d/custom.fact

    - name: Re-read facts after adding custom fact
      setup:
        filter: ansible_local
      register: ansible_local
    - debug:
        var: ansible_local
