---
- name: Create a new primary partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 800MB

- name: Create a new logical group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1

- name: Create a new logical volume
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512M
    state: present

- name: Create a XFS filesystem on the logical volume lv_mysql
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql
    
- name: Logical volume is permanently mounted
  mount:
    path: /mnt/mysql_backup
    src: dev/vsg_database/lv_mysql
    state: mounted
    fstype: xfs

- name: Install packages
  package:
    name:
    - mariadb-server

- name: Allow all incoming traffic on mySQL
  firewalld:
    service: mysql
    permanent: yes
    immediate: yes
    state: enabled

- name: configure root user
  mysql_user:
    check_implicit_admin: true
    login_host: localhost
    login_user: root
    login_password: ''
    name: root
    password: "{{ database_password }}"
    state: present

- name: start and enable mysql
  service:
    name: mysqld
    state: started
    enabled: true

- name: Deploy configure
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
